language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Squeak-5.1
  - Squeak-5.0
  - Squeak-trunk

matrix:
  allow_failures:
    - smalltalk: Squeak-trunk
